### ISSUE TITLE
Inner Components for posts and custom post types

### ISSUE THREAD

**Issue by IkeTen** [dtbaker/stylepress#1]
@dtbaker  will there be inner Inner Components for posts and custom post types? If not please add. That's where the real meat of the plugin will be, the ability to globally style Custom post types. Good work! Am testing it out now

**Comment by dtbaker** [comment]
Yes this will be the next update. "Inner" stuff is currently disabled in
1.0.9 so don't bother testing that

**Comment by IkeTen** [comment]
Ok.
