### ISSUE TITLE
How to insert HTML code in to <head>

### ISSUE THREAD

**Issue by kieusonlam** [dtbaker/stylepress#19]
I'm trying to insert Tracking code into my theme, I insert it into theme file but it's not showing up.

**Comment by norewp** [comment]
You need to give specific information i.e. what theme, how and where did you insert the code plus how did you check to acertain that it didn't work.

The more info you give the easier it is for to test and the quicker we can get you an answer.

**Comment by kieusonlam** [comment]
Hm, it's quite long time ago. I think maybe I found the answer - not remember :). So I close this for now. Thanks for reply anyway.
