### ISSUE TITLE
walker-display.php is missing

### ISSUE THREAD

**Issue by WPDevHQ** [dtbaker/stylepress#2]
Just installed the latest version and got the following Warning
`Warning: require_once(C:\laragon\www\WooCommerce\wp-content\plugins\stylepress-for-elementor/extensions/wp-menu/walker-display.php): failed to open stream: No such file or directory in C:\laragon\www\WooCommerce\wp-content\plugins\stylepress-for-elementor\extensions\wp-menu\wp-menu.php on line 23`

I had to set the folder name to `stylepress-for-elementor` since `stylepress` alone prompts an update with the 7 year old pluhin in the repository.

**Comment by dtbaker** [comment]
All fixed
