### ISSUE TITLE
Elementor and Style Press not working together anymore

### ISSUE THREAD

**Issue by raymondkent** [dtbaker/stylepress#22]
Hi,
Recent plugin updates and now I cant get elementor to launch. I can see the edit with Elementor in WP, but when I select that option I get to see the page I want to edit, but no Elementor controls at all.

When trying to edit StylePress template same issue.

Running:
Wordpress 4.8
StylePress V1.0.18
Elementor V1.5.2
Storefront theme for woocommerce V2.2.4 and latest version of Woocommerce.

Any ideas?

Thanks

**Comment by dtbaker** [comment]
Thanks for reporting this, I'll check it out now

**Comment by raymondkent** [comment]
Hi there,

I have just done more troubleshooting and it's not Style press.

There is a conflict with Elementor and another plugin. I am not sure which
one as yet, bit it's also screwing up my wp membership plugin.

So nothing wrong with Styles read. In fact Stylepress is  awesome!
