### ISSUE TITLE
entry-header class in generatepress

### ISSUE THREAD

**Issue by dasigna** [dtbaker/stylepress#4]
three times already where stylepress in combination with generatepress causes an issue with some '.entry-header' class that applies a white background to headlines...
as this is not desired to be so by default (and even ugly when having other bg colors) i wonder why this is applied by stylepress...
cant see any reason behind this, so would be highly recommended if that would be wiped out in upcoming version (even if can be over written by custom css - but thats an unnecessary task)

thanks :-)

btw.
despite seeing that there is some developing going on behind the curtains it would be really great to get some info how cpt's and especially custom fields for them (!) might be included in stylepress templates.
already posted questions on wordpress repo site, but sadly still no answer.
appreciate if there might be some soon. big thanks in advance.

**Comment by dtbaker** [comment]
Please try the latest update, we've added support for generatepress. If this continues to be a problem please post a screenshot or a link to the page so we can check it out.
