### ISSUE TITLE
Stylepress menu Widget - Icon List 

### ISSUE THREAD

**Issue by ianlucasdiaz** [dtbaker/stylepress#9]
Hello, 

Since the new update, an icon list has appeared in my nav menu, ruining the looks of it.
I have added some CSS to put back the background color for the nav menu, but menu buttons are not centered anymore, and i cant seem to delete all icon lists from elementor.

Can we please add an option if we want to use icon list in out nav bar?

And can you tell me how to set it back to full width again?

Please for future updates:
Dont add default setting to widgets on updates, its breaking the theme looks.

thx.

**Comment by ianlucasdiaz** [comment]
![image](https://cloud.githubusercontent.com/assets/27924800/25315951/4a76fc34-2834-11e7-9695-f4f63ca60a22.png)
 Nav menu also now has some space between pages (a) items..
How can i make it so that space is gone?

**Comment by bodhi1970** [comment]
The icons are a great feature but it is not thought through. The update messes up the whole header. Please fix that asap.

**Comment by pingram3541** [comment]
The unordered list (ul) needs to have the font-size reset to zero and then the font-size you desire set back on the list-item (li) or the anchor tag (a), for example:

ul#main_menu {
  font-size: 0;
}
ul#main_menu li.menu-item a {
  font-size: 15px;
}

**Comment by pingram3541** [comment]
If you don't have Elementor pro w/ custom css you can add custom css via an html element and adding `<script></script>` tags or you can add it using the WordPress Customizer.  Just find suitable target id's or classes to match similarly with the example above and you should be good to go until this gets squashed.  I haven't upgraded yet to see how it effects one of my sites but I'll report back if I experience the same.

**Comment by dtbaker** [comment]
Jump into the menu widget settings and remove the icon list from the Elementor configuration. See if that helps.

**Comment by pingram3541** [comment]
@dtbaker How does one remove the last list-item?

**Comment by dtbaker** [comment]
@pingram3541 please try the latest update, it includes a toggle for showing the icon list

**Comment by pingram3541** [comment]
Perfect, it works!  Maybe consider adding some styling options for the logo part.  Currently one has to use custom css to change the size/margin/padding.  Thx

**Comment by bodhi1970** [comment]
Still can’t figure out how to set menu centered or right. Have used css for nice view.

Dropdown menu does not work either. When I go down with mouse and pass edge of section, the menu disappears.
